services:

  web:

    build: .

    container_name: app-devops

    ports:
      - "8002:8002"

    restart: always

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"
        ]

      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
